### ISSUE TITLE
go generate error

### ISSUE THREAD

**Issue by isBigChen** [dkorunic/pktstat-bpf#1]
thank you for your code, but i run go generate, it had a bug, could you please help me solve this error
```root@ubuntu22:~/pktstat-bpf-main/pktstat-bpf-main# go generate
In file included from /root/pktstat-bpf-main/pktstat-bpf-main/counter.c:24:
In file included from /usr/include/linux/bpf.h:11:
/usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
Error: compile: exit status 1
exit status 1
gen.go:24: running "go": exit status 1```

**Comment by dkorunic** [comment]
@isBigChen When you decide to recompile eBPF program itself, your Linux development installation has to be fully complete -- so you have to at least have linux-libc-dev, clang, llvm-strip, libbpf headers and Linux kernel headers, as stated in ebfp-go [getting-started](https://ebpf-go.dev/guides/getting-started/).
I don't think there is any need to compile eBPF program though, since repository contains already compiled CO:RE binaries, for littleendan and bigendian platforms, so if anything just Go binary can be recompiled. Or even better, just use already compiled full binaries.
